--[[
	UpgradeCatalog.lua

	GENERATED from Route_Rush_Equipment_List.xlsx ("All 180 Upgrades" sheet).
	Do not hand-edit; regenerate from the spreadsheet instead.

	UpgradeCatalog.Get(chassisId, category, level) -> { name, visual, stat } or nil
]]

local UpgradeCatalog = {}

UpgradeCatalog.Entries = {
	Tier1 = {
		Engine = {
			[1] = { name = "Patched Piston Job", visual = "Patched hood with a visible rust repair; a single small tailpipe puffs white smoke.", stat = "Top speed under load" },
			[2] = { name = "Rickshaw-Shop Rebore", visual = "Reinforced hood latch; slightly larger tailpipe; oil stains visible through the hood vents.", stat = "Top speed under load" },
			[3] = { name = "Local Garage Bore-Out", visual = "A second exhaust pipe added; small hood-scoop bump appears.", stat = "Top speed under load" },
			[4] = { name = "Bazaar Turbo Kit", visual = "Audible turbo whistle on acceleration; chrome side pipes and a small hood scoop.", stat = "Top speed under load" },
			[5] = { name = "Dhaka Road Warrior Cam", visual = "Twin chrome exhaust stacks; mesh hood vents; a faint engine glow visible at idle.", stat = "Top speed under load" },
			[6] = { name = "Twin-Carb Hustle", visual = "Raised hood section with an intercooler pipe visible; dual side exhausts shimmer with heat haze.", stat = "Top speed under load" },
			[7] = { name = "Highway Tuned Block", visual = "Exposed turbo manifold visible under a clear inspection panel; quad exhaust tips.", stat = "Top speed under load" },
			[8] = { name = "Chittagong Port Import Engine", visual = "Cutaway hood panel reveals a custom-painted engine bay; quad chrome stacks with flame decals.", stat = "Top speed under load" },
			[9] = { name = "Black-Market Rocket Block", visual = "Fully chromed, glowing engine bay visible through the hood; quad stacks visibly flare on boost.", stat = "Top speed under load" },
		},
		Accel = {
			[1] = { name = "Loose Belt Tighten", visual = "Slightly wider rear tires with a basic tread pattern; no visible stance change.", stat = "0-to-full throttle time" },
			[2] = { name = "Patched Carburetor Tune", visual = "Reinforced rear axle just visible under the body; stance sits a touch lower.", stat = "0-to-full throttle time" },
			[3] = { name = "Local Shop Throttle Kit", visual = "Grippier performance tire compound with a visibly deeper tread pattern.", stat = "0-to-full throttle time" },
			[4] = { name = "Bazaar Quick-Start Kit", visual = "Wider rear tire stance; subtle rear-end squat animation on hard launch.", stat = "0-to-full throttle time" },
			[5] = { name = "Roadside Launch Tune", visual = "Drag-style rear tires; light tire smoke puffs on hard acceleration.", stat = "0-to-full throttle time" },
			[6] = { name = "Dhaka Sprint Special", visual = "Nitrous-style canister decals on the rear side panels; bigger tire smoke on launch.", stat = "0-to-full throttle time" },
			[7] = { name = "Highway Launch Package", visual = "Racing slicks on the rear axle; visible rear suspension flex animation under power.", stat = "0-to-full throttle time" },
			[8] = { name = "Chittagong Nitro Import", visual = "Launch-control light flashes on the dash readout; larger smoke plume at start.", stat = "0-to-full throttle time" },
			[9] = { name = "Black-Market Rocket Start", visual = "Full drag-race rear tire setup with a flame-pop exhaust crackle on launch.", stat = "0-to-full throttle time" },
		},
		Brakes = {
			[1] = { name = "Rusty Drum Fix", visual = "Worn drum brakes with visible surface rust on the rims.", stat = "Stopping distance at full load" },
			[2] = { name = "Patched Brake Pads", visual = "Repainted drum brakes; small brake-dust shield plates added.", stat = "Stopping distance at full load" },
			[3] = { name = "Local Shop Disc Swap", visual = "Front disc brake conversion — a rotor is now visible through the wheel spokes.", stat = "Stopping distance at full load" },
			[4] = { name = "Bazaar Big-Brake Kit", visual = "Cross-drilled rotors with calipers repainted a visible red.", stat = "Stopping distance at full load" },
			[5] = { name = "Roadside Rotor Upgrade", visual = "Big-brake kit: 4-piston calipers and noticeably larger rotors.", stat = "Stopping distance at full load" },
			[6] = { name = "Dhaka Traffic Stopper", visual = "Ventilated rotor set with a faint heat-glow decal at the rotor edge.", stat = "Stopping distance at full load" },
			[7] = { name = "Highway Brake Special", visual = "Racing caliper kit with visible braided brake lines and a dash ABS indicator.", stat = "Stopping distance at full load" },
			[8] = { name = "Chittagong Caliper Import", visual = "Carbon-ceramic-look rotors with glowing caliper accent trim.", stat = "Stopping distance at full load" },
			[9] = { name = "Black-Market Brake Beast", visual = "Full racing brake package — a light smoke-haze effect appears on hard stops.", stat = "Stopping distance at full load" },
		},
		Handles = {
			[1] = { name = "Extra Standing Rail", visual = "A single extra standing rail installed just inside the door.", stat = "Max passengers + cornering stability" },
			[2] = { name = "Patched Aisle Jump Seats", visual = "Fold-down jump seats added along the aisle.", stat = "Max passengers + cornering stability" },
			[3] = { name = "Local Shop Roof Rack", visual = "A roof-rack platform added for extra standing room and luggage overflow.", stat = "Max passengers + cornering stability" },
			[4] = { name = "Bazaar Rear Platform", visual = "An extended rear bumper platform for hanger-on riders.", stat = "Max passengers + cornering stability" },
			[5] = { name = "Roadside Wide-Door Kit", visual = "Double doors widened for faster boarding and more standees.", stat = "Max passengers + cornering stability" },
			[6] = { name = "Dhaka Rooftop Bench", visual = "A rooftop bench added for open-air rooftop riders.", stat = "Max passengers + cornering stability" },
			[7] = { name = "Highway Extended Frame", visual = "Chassis visibly extended with an added row of seating.", stat = "Max passengers + cornering stability" },
			[8] = { name = "Chittagong Deck Import", visual = "Reinforced roof deck built out for maximum rooftop capacity.", stat = "Max passengers + cornering stability" },
			[9] = { name = "Black-Market Max-Pack Kit", visual = "Fully extended, double-capacity livery — passenger figures visibly packed on every surface, including the roof.", stat = "Max passengers + cornering stability" },
		},
		Health = {
			[1] = { name = "Patchwork Panel Fix", visual = "Patched body panels with visible weld-seam repair marks.", stat = "Collision / weapon damage resistance" },
			[2] = { name = "Local Shop Weld Job", visual = "Extra flat steel braces bolted across the exterior body panels.", stat = "Collision / weapon damage resistance" },
			[3] = { name = "Bazaar Bumper Reinforce", visual = "Reinforced bumper bars added front and rear.", stat = "Collision / weapon damage resistance" },
			[4] = { name = "Roadside Frame Brace", visual = "Metal side-guard rails installed along the lower body line.", stat = "Collision / weapon damage resistance" },
			[5] = { name = "Dhaka Street Armor", visual = "Undercarriage skid plate visible beneath the front bumper.", stat = "Collision / weapon damage resistance" },
			[6] = { name = "Highway Guard Plating", visual = "Full body-cage reinforcement bars visible through the window line.", stat = "Collision / weapon damage resistance" },
			[7] = { name = "Chittagong Steel Import", visual = "Armor plating bolted onto the doors and hood.", stat = "Collision / weapon damage resistance" },
			[8] = { name = "Black-Market Armor Kit", visual = "Reinforced roll-cage frame visible along the roofline.", stat = "Collision / weapon damage resistance" },
			[9] = { name = "Legendary Iron Hull", visual = "Full armored livery: riveted steel plating and reinforced window grates.", stat = "Collision / weapon damage resistance" },
		},
	},
	Tier2 = {
		Engine = {
			[1] = { name = "City Workshop Tune-Up", visual = "Patched hood with a visible rust repair; a single small tailpipe puffs white smoke.", stat = "Top speed under load" },
			[2] = { name = "Reinforced Cylinder Head", visual = "Reinforced hood latch; slightly larger tailpipe; oil stains visible through the hood vents.", stat = "Top speed under load" },
			[3] = { name = "Dual-Injector Swap", visual = "A second exhaust pipe added; small hood-scoop bump appears.", stat = "Top speed under load" },
			[4] = { name = "Turbo City Special", visual = "Audible turbo whistle on acceleration; chrome side pipes and a small hood scoop.", stat = "Top speed under load" },
			[5] = { name = "Intercooled Street Block", visual = "Twin chrome exhaust stacks; mesh hood vents; a faint engine glow visible at idle.", stat = "Top speed under load" },
			[6] = { name = "Sylhet Tuned V4", visual = "Raised hood section with an intercooler pipe visible; dual side exhausts shimmer with heat haze.", stat = "Top speed under load" },
			[7] = { name = "Express Route Powerplant", visual = "Exposed turbo manifold visible under a clear inspection panel; quad exhaust tips.", stat = "Top speed under load" },
			[8] = { name = "Comilla Motor Works Special", visual = "Cutaway hood panel reveals a custom-painted engine bay; quad chrome stacks with flame decals.", stat = "Top speed under load" },
			[9] = { name = "Metro Line Monster Block", visual = "Fully chromed, glowing engine bay visible through the hood; quad stacks visibly flare on boost.", stat = "Top speed under load" },
		},
		Accel = {
			[1] = { name = "City Throttle Tune", visual = "Slightly wider rear tires with a basic tread pattern; no visible stance change.", stat = "0-to-full throttle time" },
			[2] = { name = "Reinforced Clutch Kit", visual = "Reinforced rear axle just visible under the body; stance sits a touch lower.", stat = "0-to-full throttle time" },
			[3] = { name = "Dual-Stage Throttle Body", visual = "Grippier performance tire compound with a visibly deeper tread pattern.", stat = "0-to-full throttle time" },
			[4] = { name = "Street Sprint Package", visual = "Wider rear tire stance; subtle rear-end squat animation on hard launch.", stat = "0-to-full throttle time" },
			[5] = { name = "Metro Quick-Launch Kit", visual = "Drag-style rear tires; light tire smoke puffs on hard acceleration.", stat = "0-to-full throttle time" },
			[6] = { name = "Sylhet Tuned Launch Set", visual = "Nitrous-style canister decals on the rear side panels; bigger tire smoke on launch.", stat = "0-to-full throttle time" },
			[7] = { name = "Express Route Sprinter", visual = "Racing slicks on the rear axle; visible rear suspension flex animation under power.", stat = "0-to-full throttle time" },
			[8] = { name = "Comilla Speed Works Kit", visual = "Launch-control light flashes on the dash readout; larger smoke plume at start.", stat = "0-to-full throttle time" },
			[9] = { name = "Metro Line Launch Beast", visual = "Full drag-race rear tire setup with a flame-pop exhaust crackle on launch.", stat = "0-to-full throttle time" },
		},
		Brakes = {
			[1] = { name = "City Pad Refresh", visual = "Worn drum brakes with visible surface rust on the rims.", stat = "Stopping distance at full load" },
			[2] = { name = "Reinforced Shoe Set", visual = "Repainted drum brakes; small brake-dust shield plates added.", stat = "Stopping distance at full load" },
			[3] = { name = "Dual-Piston Disc Kit", visual = "Front disc brake conversion — a rotor is now visible through the wheel spokes.", stat = "Stopping distance at full load" },
			[4] = { name = "Street Special Rotors", visual = "Cross-drilled rotors with calipers repainted a visible red.", stat = "Stopping distance at full load" },
			[5] = { name = "Metro Stopper Package", visual = "Big-brake kit: 4-piston calipers and noticeably larger rotors.", stat = "Stopping distance at full load" },
			[6] = { name = "Sylhet Tuned Brake Set", visual = "Ventilated rotor set with a faint heat-glow decal at the rotor edge.", stat = "Stopping distance at full load" },
			[7] = { name = "Express Route Anchors", visual = "Racing caliper kit with visible braided brake lines and a dash ABS indicator.", stat = "Stopping distance at full load" },
			[8] = { name = "Comilla Brake Works Kit", visual = "Carbon-ceramic-look rotors with glowing caliper accent trim.", stat = "Stopping distance at full load" },
			[9] = { name = "Metro Line Iron Grip", visual = "Full racing brake package — a light smoke-haze effect appears on hard stops.", stat = "Stopping distance at full load" },
		},
		Handles = {
			[1] = { name = "City Aisle Extension", visual = "A single extra standing rail installed just inside the door.", stat = "Max passengers + cornering stability" },
			[2] = { name = "Reinforced Standee Rails", visual = "Fold-down jump seats added along the aisle.", stat = "Max passengers + cornering stability" },
			[3] = { name = "Dual-Door Boarding Kit", visual = "A roof-rack platform added for extra standing room and luggage overflow.", stat = "Max passengers + cornering stability" },
			[4] = { name = "Street Rooftop Platform", visual = "An extended rear bumper platform for hanger-on riders.", stat = "Max passengers + cornering stability" },
			[5] = { name = "Metro Wide-Bay Package", visual = "Double doors widened for faster boarding and more standees.", stat = "Max passengers + cornering stability" },
			[6] = { name = "Sylhet Tuned Deck Set", visual = "A rooftop bench added for open-air rooftop riders.", stat = "Max passengers + cornering stability" },
			[7] = { name = "Express Route Extender", visual = "Chassis visibly extended with an added row of seating.", stat = "Max passengers + cornering stability" },
			[8] = { name = "Comilla Capacity Works Kit", visual = "Reinforced roof deck built out for maximum rooftop capacity.", stat = "Max passengers + cornering stability" },
			[9] = { name = "Metro Line Max Capacity Beast", visual = "Fully extended, double-capacity livery — passenger figures visibly packed on every surface, including the roof.", stat = "Max passengers + cornering stability" },
		},
		Health = {
			[1] = { name = "City Panel Reinforce", visual = "Patched body panels with visible weld-seam repair marks.", stat = "Collision / weapon damage resistance" },
			[2] = { name = "Reinforced Frame Kit", visual = "Extra flat steel braces bolted across the exterior body panels.", stat = "Collision / weapon damage resistance" },
			[3] = { name = "Dual-Layer Bumper Set", visual = "Reinforced bumper bars added front and rear.", stat = "Collision / weapon damage resistance" },
			[4] = { name = "Street Guard Plating", visual = "Metal side-guard rails installed along the lower body line.", stat = "Collision / weapon damage resistance" },
			[5] = { name = "Metro Armor Package", visual = "Undercarriage skid plate visible beneath the front bumper.", stat = "Collision / weapon damage resistance" },
			[6] = { name = "Sylhet Tuned Hull Set", visual = "Full body-cage reinforcement bars visible through the window line.", stat = "Collision / weapon damage resistance" },
			[7] = { name = "Express Route Ironclad", visual = "Armor plating bolted onto the doors and hood.", stat = "Collision / weapon damage resistance" },
			[8] = { name = "Comilla Steel Works Kit", visual = "Reinforced roll-cage frame visible along the roofline.", stat = "Collision / weapon damage resistance" },
			[9] = { name = "Metro Line Iron Giant", visual = "Full armored livery: riveted steel plating and reinforced window grates.", stat = "Collision / weapon damage resistance" },
		},
	},
	Tier3 = {
		Engine = {
			[1] = { name = "Fleet-Grade Overhaul", visual = "Patched hood with a visible rust repair; a single small tailpipe puffs white smoke.", stat = "Top speed under load" },
			[2] = { name = "Heavy Duty Cylinder Set", visual = "Reinforced hood latch; slightly larger tailpipe; oil stains visible through the hood vents.", stat = "Top speed under load" },
			[3] = { name = "Diesel Torque Kit", visual = "A second exhaust pipe added; small hood-scoop bump appears.", stat = "Top speed under load" },
			[4] = { name = "Highway Cruiser Turbo", visual = "Audible turbo whistle on acceleration; chrome side pipes and a small hood scoop.", stat = "Top speed under load" },
			[5] = { name = "Twin-Turbo Freight Block", visual = "Twin chrome exhaust stacks; mesh hood vents; a faint engine glow visible at idle.", stat = "Top speed under load" },
			[6] = { name = "Long-Haul Power Core", visual = "Raised hood section with an intercooler pipe visible; dual side exhausts shimmer with heat haze.", stat = "Top speed under load" },
			[7] = { name = "National Highway V8", visual = "Exposed turbo manifold visible under a clear inspection panel; quad exhaust tips.", stat = "Top speed under load" },
			[8] = { name = "Cross-Country Beast Engine", visual = "Cutaway hood panel reveals a custom-painted engine bay; quad chrome stacks with flame decals.", stat = "Top speed under load" },
			[9] = { name = "Grand Trunk Road Titan", visual = "Fully chromed, glowing engine bay visible through the hood; quad stacks visibly flare on boost.", stat = "Top speed under load" },
		},
		Accel = {
			[1] = { name = "Fleet Throttle Overhaul", visual = "Slightly wider rear tires with a basic tread pattern; no visible stance change.", stat = "0-to-full throttle time" },
			[2] = { name = "Heavy Duty Clutch Set", visual = "Reinforced rear axle just visible under the body; stance sits a touch lower.", stat = "0-to-full throttle time" },
			[3] = { name = "Diesel Launch Kit", visual = "Grippier performance tire compound with a visibly deeper tread pattern.", stat = "0-to-full throttle time" },
			[4] = { name = "Highway Cruiser Sprint Pack", visual = "Wider rear tire stance; subtle rear-end squat animation on hard launch.", stat = "0-to-full throttle time" },
			[5] = { name = "Twin-Turbo Launch System", visual = "Drag-style rear tires; light tire smoke puffs on hard acceleration.", stat = "0-to-full throttle time" },
			[6] = { name = "Long-Haul Sprint Core", visual = "Nitrous-style canister decals on the rear side panels; bigger tire smoke on launch.", stat = "0-to-full throttle time" },
			[7] = { name = "National Highway Launch Kit", visual = "Racing slicks on the rear axle; visible rear suspension flex animation under power.", stat = "0-to-full throttle time" },
			[8] = { name = "Cross-Country Sprint Beast", visual = "Launch-control light flashes on the dash readout; larger smoke plume at start.", stat = "0-to-full throttle time" },
			[9] = { name = "Grand Trunk Road Rocket", visual = "Full drag-race rear tire setup with a flame-pop exhaust crackle on launch.", stat = "0-to-full throttle time" },
		},
		Brakes = {
			[1] = { name = "Fleet Brake Overhaul", visual = "Worn drum brakes with visible surface rust on the rims.", stat = "Stopping distance at full load" },
			[2] = { name = "Heavy Duty Shoe Set", visual = "Repainted drum brakes; small brake-dust shield plates added.", stat = "Stopping distance at full load" },
			[3] = { name = "Diesel-Rated Disc Kit", visual = "Front disc brake conversion — a rotor is now visible through the wheel spokes.", stat = "Stopping distance at full load" },
			[4] = { name = "Highway Cruiser Stoppers", visual = "Cross-drilled rotors with calipers repainted a visible red.", stat = "Stopping distance at full load" },
			[5] = { name = "Twin-Circuit Brake System", visual = "Big-brake kit: 4-piston calipers and noticeably larger rotors.", stat = "Stopping distance at full load" },
			[6] = { name = "Long-Haul Anchor Set", visual = "Ventilated rotor set with a faint heat-glow decal at the rotor edge.", stat = "Stopping distance at full load" },
			[7] = { name = "National Highway Grip Kit", visual = "Racing caliper kit with visible braided brake lines and a dash ABS indicator.", stat = "Stopping distance at full load" },
			[8] = { name = "Cross-Country Brake Beast", visual = "Carbon-ceramic-look rotors with glowing caliper accent trim.", stat = "Stopping distance at full load" },
			[9] = { name = "Grand Trunk Road Iron Fist", visual = "Full racing brake package — a light smoke-haze effect appears on hard stops.", stat = "Stopping distance at full load" },
		},
		Handles = {
			[1] = { name = "Fleet Aisle Overhaul", visual = "A single extra standing rail installed just inside the door.", stat = "Max passengers + cornering stability" },
			[2] = { name = "Heavy Duty Standee Set", visual = "Fold-down jump seats added along the aisle.", stat = "Max passengers + cornering stability" },
			[3] = { name = "Diesel-Rated Door Kit", visual = "A roof-rack platform added for extra standing room and luggage overflow.", stat = "Max passengers + cornering stability" },
			[4] = { name = "Highway Cruiser Deck Pack", visual = "An extended rear bumper platform for hanger-on riders.", stat = "Max passengers + cornering stability" },
			[5] = { name = "Twin-Bay Boarding System", visual = "Double doors widened for faster boarding and more standees.", stat = "Max passengers + cornering stability" },
			[6] = { name = "Long-Haul Rooftop Core", visual = "A rooftop bench added for open-air rooftop riders.", stat = "Max passengers + cornering stability" },
			[7] = { name = "National Highway Extender Kit", visual = "Chassis visibly extended with an added row of seating.", stat = "Max passengers + cornering stability" },
			[8] = { name = "Cross-Country Capacity Beast", visual = "Reinforced roof deck built out for maximum rooftop capacity.", stat = "Max passengers + cornering stability" },
			[9] = { name = "Grand Trunk Road Max-Pack", visual = "Fully extended, double-capacity livery — passenger figures visibly packed on every surface, including the roof.", stat = "Max passengers + cornering stability" },
		},
		Health = {
			[1] = { name = "Fleet Frame Overhaul", visual = "Patched body panels with visible weld-seam repair marks.", stat = "Collision / weapon damage resistance" },
			[2] = { name = "Heavy Duty Panel Set", visual = "Extra flat steel braces bolted across the exterior body panels.", stat = "Collision / weapon damage resistance" },
			[3] = { name = "Diesel-Rated Bumper Kit", visual = "Reinforced bumper bars added front and rear.", stat = "Collision / weapon damage resistance" },
			[4] = { name = "Highway Cruiser Guard Pack", visual = "Metal side-guard rails installed along the lower body line.", stat = "Collision / weapon damage resistance" },
			[5] = { name = "Twin-Layer Armor System", visual = "Undercarriage skid plate visible beneath the front bumper.", stat = "Collision / weapon damage resistance" },
			[6] = { name = "Long-Haul Ironclad Core", visual = "Full body-cage reinforcement bars visible through the window line.", stat = "Collision / weapon damage resistance" },
			[7] = { name = "National Highway Steel Kit", visual = "Armor plating bolted onto the doors and hood.", stat = "Collision / weapon damage resistance" },
			[8] = { name = "Cross-Country Armor Beast", visual = "Reinforced roll-cage frame visible along the roofline.", stat = "Collision / weapon damage resistance" },
			[9] = { name = "Grand Trunk Road Fortress", visual = "Full armored livery: riveted steel plating and reinforced window grates.", stat = "Collision / weapon damage resistance" },
		},
	},
	Tier4 = {
		Engine = {
			[1] = { name = "Dual-Axle Power Base", visual = "Patched hood with a visible rust repair; a single small tailpipe puffs white smoke.", stat = "Top speed under load" },
			[2] = { name = "Reinforced Articulation Block", visual = "Reinforced hood latch; slightly larger tailpipe; oil stains visible through the hood vents.", stat = "Top speed under load" },
			[3] = { name = "Twin-Deck Turbo Core", visual = "A second exhaust pipe added; small hood-scoop bump appears.", stat = "Top speed under load" },
			[4] = { name = "Megacity Torque Engine", visual = "Audible turbo whistle on acceleration; chrome side pipes and a small hood scoop.", stat = "Top speed under load" },
			[5] = { name = "Skyline Double Turbo", visual = "Twin chrome exhaust stacks; mesh hood vents; a faint engine glow visible at idle.", stat = "Top speed under load" },
			[6] = { name = "Continental Freight Core", visual = "Raised hood section with an intercooler pipe visible; dual side exhausts shimmer with heat haze.", stat = "Top speed under load" },
			[7] = { name = "Imperial Highway V12", visual = "Exposed turbo manifold visible under a clear inspection panel; quad exhaust tips.", stat = "Top speed under load" },
			[8] = { name = "Sovereign Grand Engine", visual = "Cutaway hood panel reveals a custom-painted engine bay; quad chrome stacks with flame decals.", stat = "Top speed under load" },
			[9] = { name = "Legendary Route King Powerplant", visual = "Fully chromed, glowing engine bay visible through the hood; quad stacks visibly flare on boost.", stat = "Top speed under load" },
		},
		Accel = {
			[1] = { name = "Dual-Axle Launch Base", visual = "Slightly wider rear tires with a basic tread pattern; no visible stance change.", stat = "0-to-full throttle time" },
			[2] = { name = "Reinforced Articulation Sprint Kit", visual = "Reinforced rear axle just visible under the body; stance sits a touch lower.", stat = "0-to-full throttle time" },
			[3] = { name = "Twin-Deck Launch Package", visual = "Grippier performance tire compound with a visibly deeper tread pattern.", stat = "0-to-full throttle time" },
			[4] = { name = "Megacity Sprint Core", visual = "Wider rear tire stance; subtle rear-end squat animation on hard launch.", stat = "0-to-full throttle time" },
			[5] = { name = "Skyline Launch System", visual = "Drag-style rear tires; light tire smoke puffs on hard acceleration.", stat = "0-to-full throttle time" },
			[6] = { name = "Continental Sprint Set", visual = "Nitrous-style canister decals on the rear side panels; bigger tire smoke on launch.", stat = "0-to-full throttle time" },
			[7] = { name = "Imperial Launch Package", visual = "Racing slicks on the rear axle; visible rear suspension flex animation under power.", stat = "0-to-full throttle time" },
			[8] = { name = "Sovereign Sprint Beast", visual = "Launch-control light flashes on the dash readout; larger smoke plume at start.", stat = "0-to-full throttle time" },
			[9] = { name = "Legendary Route King Launch", visual = "Full drag-race rear tire setup with a flame-pop exhaust crackle on launch.", stat = "0-to-full throttle time" },
		},
		Brakes = {
			[1] = { name = "Dual-Axle Brake Base", visual = "Worn drum brakes with visible surface rust on the rims.", stat = "Stopping distance at full load" },
			[2] = { name = "Reinforced Articulation Stoppers", visual = "Repainted drum brakes; small brake-dust shield plates added.", stat = "Stopping distance at full load" },
			[3] = { name = "Twin-Deck Disc Package", visual = "Front disc brake conversion — a rotor is now visible through the wheel spokes.", stat = "Stopping distance at full load" },
			[4] = { name = "Megacity Brake Core", visual = "Cross-drilled rotors with calipers repainted a visible red.", stat = "Stopping distance at full load" },
			[5] = { name = "Skyline Stopping System", visual = "Big-brake kit: 4-piston calipers and noticeably larger rotors.", stat = "Stopping distance at full load" },
			[6] = { name = "Continental Anchor Set", visual = "Ventilated rotor set with a faint heat-glow decal at the rotor edge.", stat = "Stopping distance at full load" },
			[7] = { name = "Imperial Grip Package", visual = "Racing caliper kit with visible braided brake lines and a dash ABS indicator.", stat = "Stopping distance at full load" },
			[8] = { name = "Sovereign Brake Beast", visual = "Carbon-ceramic-look rotors with glowing caliper accent trim.", stat = "Stopping distance at full load" },
			[9] = { name = "Legendary Route King Anchors", visual = "Full racing brake package — a light smoke-haze effect appears on hard stops.", stat = "Stopping distance at full load" },
		},
		Handles = {
			[1] = { name = "Dual-Axle Capacity Base", visual = "A single extra standing rail installed just inside the door.", stat = "Max passengers + cornering stability" },
			[2] = { name = "Reinforced Articulation Deck", visual = "Fold-down jump seats added along the aisle.", stat = "Max passengers + cornering stability" },
			[3] = { name = "Twin-Deck Boarding Package", visual = "A roof-rack platform added for extra standing room and luggage overflow.", stat = "Max passengers + cornering stability" },
			[4] = { name = "Megacity Capacity Core", visual = "An extended rear bumper platform for hanger-on riders.", stat = "Max passengers + cornering stability" },
			[5] = { name = "Skyline Rooftop System", visual = "Double doors widened for faster boarding and more standees.", stat = "Max passengers + cornering stability" },
			[6] = { name = "Continental Deck Set", visual = "A rooftop bench added for open-air rooftop riders.", stat = "Max passengers + cornering stability" },
			[7] = { name = "Imperial Capacity Package", visual = "Chassis visibly extended with an added row of seating.", stat = "Max passengers + cornering stability" },
			[8] = { name = "Sovereign Max-Pack Beast", visual = "Reinforced roof deck built out for maximum rooftop capacity.", stat = "Max passengers + cornering stability" },
			[9] = { name = "Legendary Route King Mega-Deck", visual = "Fully extended, double-capacity livery — passenger figures visibly packed on every surface, including the roof.", stat = "Max passengers + cornering stability" },
		},
		Health = {
			[1] = { name = "Dual-Axle Armor Base", visual = "Patched body panels with visible weld-seam repair marks.", stat = "Collision / weapon damage resistance" },
			[2] = { name = "Reinforced Articulation Hull", visual = "Extra flat steel braces bolted across the exterior body panels.", stat = "Collision / weapon damage resistance" },
			[3] = { name = "Twin-Deck Armor Package", visual = "Reinforced bumper bars added front and rear.", stat = "Collision / weapon damage resistance" },
			[4] = { name = "Megacity Ironclad Core", visual = "Metal side-guard rails installed along the lower body line.", stat = "Collision / weapon damage resistance" },
			[5] = { name = "Skyline Fortress System", visual = "Undercarriage skid plate visible beneath the front bumper.", stat = "Collision / weapon damage resistance" },
			[6] = { name = "Continental Armor Set", visual = "Full body-cage reinforcement bars visible through the window line.", stat = "Collision / weapon damage resistance" },
			[7] = { name = "Imperial Steel Package", visual = "Armor plating bolted onto the doors and hood.", stat = "Collision / weapon damage resistance" },
			[8] = { name = "Sovereign Fortress Beast", visual = "Reinforced roll-cage frame visible along the roofline.", stat = "Collision / weapon damage resistance" },
			[9] = { name = "Legendary Route King Citadel", visual = "Full armored livery: riveted steel plating and reinforced window grates.", stat = "Collision / weapon damage resistance" },
		},
	},
}

function UpgradeCatalog.Get(chassisId, category, level)
	local tier = UpgradeCatalog.Entries[chassisId]
	local byCategory = tier and tier[category]
	return byCategory and byCategory[level] or nil
end

return UpgradeCatalog
